name: gatekeeper
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      target: ${ENV:-development}
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    volumes:
      - ./:/app
    depends_on:
      - database
      - cache
    networks:
      - gatekeeper-network

  database:
    build:
      context: .
      dockerfile: ./Dockerfile.database
      target: ${ENV:-development}
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - gatekeeper-network

  cache:
    image: redis:7
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "6376:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - gatekeeper-network

networks:
  gatekeeper-network:
    driver: bridge
