PROVIDER_CREATED_EVENT = "provider_created"
PROVIDER_DELETED_EVENT = "provider_deleted"
PROVIDER_UPDATED_EVENT = "provider_updated"
PROVIDER_VERIFIED_EVENT = "provider_verified"
PROVIDER_PASSWORD_RESET_EVENT = "provider_password_reset"
PROVIDER_ACCOUNT_RECOVERY_EVENT = "provider_account_recovery"
